<?php if ($this->isAdmin) : ?>
<ul class="sf-menu">
	<li><a
		href="<?php echo $this->url(array("controller" => "treatment", "action" => "index")) ?>">Treatments</a>
	</li>
	<li>Administration
		<ul>
			<li><a
				href="<?php echo $this->url(array("controller" => "admin_treatment", "action" => "index")) ?>">Treatments</a>
			</li>
			<li><a
				href="<?php echo $this->url(array("controller" => "admin_config", "action" => "index")) ?>">Konfiguration</a>
			</li>
			<li><a
				href="<?php echo $this->url(array("controller" => "admin_mlaexperiment2", "action" => "result")) ?>">MLA Auswertung</a>
			</li>
		</ul>
	</li>
</ul>
<?php endif; ?>
<?php if (!Zend_Auth::getInstance()->hasIdentity()) : ?>
<ul class="sf-menu">
	<li><a
		href="<?php echo $this->url(array("controller" => "login", "action" => "index")) ?>">Startseite</a>
	</li>
</ul>
<?php endif; ?>
<?php if (Zend_Auth::getInstance()->hasIdentity()) : ?>
<ul class="sf-menu">
	<li><a
		href="<?php echo $this->url(array("controller" => "login", "action" => "logout")) ?>">Logout</a>

</ul>
<?php endif; ?>
