<h1>Administration - Treatment editieren</h1>
<h2>
	<?php echo $this->treatment->name ?>
</h2>

<script>
function count(){
	var ul = document.getElementById('module_ol');
	var li = ul.getElementsByTagName('li').length;
	return li;
}

$(function() {
	$( "#available_modules li" ).draggable({
		appendTo: "body",
		helper: "clone"
	});
	
	$( "#used_modules ol" ).droppable({
		activeClass: "ui-state-default",
		hoverClass: "ui-state-hover",
		accept: ":not(.ui-sortable-helper)",
		drop: function( event, ui ) {
			$( this ).find( ".placeholder" ).remove();
			$( "<li class='questionnaire_available'>" 
					+ ui.draggable.text() + "<br /><textarea name='" + ui.draggable.attr("id") + "[]' class='admin_text'></textarea></li>" ).appendTo( this );
			}
	}).sortable({
		items: "li:not(.placeholder)",
		sort: function() {
			$( this ).removeClass( "ui-state-default" );
		}
	});

	$( "#trash" ).droppable({
		activeClass: "ui-state-default",
		hoverClass: "ui-state-hover",
		drop: function( event, ui ) {
			if(confirm('Dieses Modul wird in der jetzigen Konfiguration entfernt. Die Konfiguration wird dabei gelöscht und kann NICHT wiederhergestellt werden. Sind Sie sicher?')) {
				$(ui.draggable).remove();
			}
		}
	});

});
</script>



<div class="questionnaire_edit">

	<div id="available_modules">
		<h3>Verf&uuml;gbare Module</h3>
		<div>
			<ul>
				<?php foreach ($this->available_modules as $module) : ?>
				<li class="questionnaire_available" id="<?php echo $module->id ?>" last_used="<?php echo $module->id ?>"><?php echo $module->name ?></li>
				<?php endforeach; ?>
			</ul>
		</div>
	</div>

	<form id="treatment" method="post"
		action="<?php echo $this->url(array("controller" => "admin_treatment", "action" => "save", "id" => $this->treatment->id)) ?>"
		enctype="application/x-www-form-urlencoded">

		<div id="used_modules">
			<h3>Verwendete Module</h3>
			<div class="">
				<ol id="module_ol">
					<?php foreach ($this->used_modules as $module) : ?>
					<li class="questionnaire_available"><?php echo $module->name ?> <br />
						<!-- Button zum entfernen eines Moduls --> <textarea
							name="<?php echo $module->module_id ?>[]" class="admin_text">
							<?php echo $module->config ?>
						</textarea>
					</li>
					<?php endforeach; ?>
					<li class="placeholder">Gew&uuml;nschtes Modul hier hineinziehen</li>
				</ol>
			</div>
		</div>

		<h3>Weitere Konfiguration</h3>
		<p>
			<label>Name:</label><input name="name" type="text" value="<?php echo $this->treatment->name ?>">
			<label>Beschreibung:</label><input name="description" type="text" value="<?php echo $this->treatment->description ?>">
			<label>Userlimit:</label><input name="userlimit" type="text" value="<?php echo $this->treatment->userlimit ?>">
			<label>Reihenfolge:</label><input name="order" type="text" value="<?php echo $this->treatment->order ?>">
		</p>

		<input type="submit" value="Speichern" />
	</form>

</div>
<br />
<h3>Nicht mehr verwendete Module hier hineinziehen:</h3>
<div id="trash" class="trashbin"></div>
