<script>
var userData;


$(document).ready(function(){
	userData = <?php echo $this->post ?>;
	//userData = {"0.77":[3400,-2000,1600,-1400,2200,-5400,4400,-1800,6600,1200,1800,1200,0,2800,-5600,-1000,3400,6800,2200,800,-2000]};
	$("#dialog").modal("show");
});

setTimeout("drawCharts();", 100);

</script>
<h1>Erfahrungen sammeln</h1>
<br>
	<button id="back" class="btn">Andere Verteilungen ausprobieren</button>
	<button id="next" class="btn">Erfahrungen sammeln beenden</button>
<div id="charts"></div>
<div id="dialog" class="modal hide">
  <div class="modal-header">
    <h3>Bitte warten</h3>
  </div>
  <div class="modal-body">
    <p>Ihre gewählten Verteilungen werden berechnet...</p>
  </div>
</div>

<script>
	$('#back').click(function() {
		window.location = "<?php echo $this->url(array("controller" => "rs_plot", "action" => "index")) ?>";
	 });
	$('#next').click(function() {
		window.location = "<?php echo $this->url(array("controller" => "rs_plot", "action" => "next")) ?>";
 	});
</script>