<?php
$objPHPExcel = new PHPExcel();
$objPHPExcel->getProperties()->setCreator("IBF Tool");
$objPHPExcel->getProperties()->setLastModifiedBy("IBF Tool");
$objPHPExcel->getProperties()->setTitle("IBF Tool - MLA Report");
$objPHPExcel->getProperties()->setSubject("IBF Tool - MLA Report");
$objPHPExcel->getProperties()->setDescription("Generated Report for a Module, by IBF Tool.");

$money = new PHPExcel_Worksheet($objPHPExcel);
$money->setTitle("Money");
$yield = new PHPExcel_Worksheet($objPHPExcel);
$yield->setTitle("Yield");
$outcome = new PHPExcel_Worksheet($objPHPExcel);
$outcome->setTitle("Outcome");
$investment = new PHPExcel_Worksheet($objPHPExcel);
$investment->setTitle("Investment");

$objPHPExcel->addSheet($money, 0);
$objPHPExcel->addSheet($yield, 1);
$objPHPExcel->addSheet($outcome, 2);
$objPHPExcel->addSheet($investment, 3);

$objPHPExcel->setActiveSheetIndex(0);

for($i = 1; $i <= 36; $i++) {
	$objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow($i, 1, utf8_encode($i));
}

$column = 0;
$row = 2;

foreach($this->users as $user) {
	$objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow($column, $row, utf8_encode($user->userhash));
	$objPHPExcel->getSheet(1)->setCellValueByColumnAndRow($column, $row, utf8_encode($user->userhash));
	$objPHPExcel->getSheet(2)->setCellValueByColumnAndRow($column, $row, utf8_encode($user->userhash));
	$objPHPExcel->getSheet(3)->setCellValueByColumnAndRow($column, $row, utf8_encode($user->userhash));
	$result = $user->findDependentRowset(new MLAExperiment_Rounds());
	
	foreach($result as $res) {
		$column++;
		$objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow($column, $row, utf8_encode($res->money));
		$objPHPExcel->getSheet(1)->setCellValueByColumnAndRow($column, $row, utf8_encode($res->yield));
		$objPHPExcel->getSheet(2)->setCellValueByColumnAndRow($column, $row, utf8_encode($res->outcome));
		$objPHPExcel->getSheet(3)->setCellValueByColumnAndRow($column, $row, utf8_encode($res->investment));
	}
	
	$row = $row+1;
	$column = 0;
}


// Save Excel 2007 file
//echo date('H:i:s') . " Write to Excel2007 format\n";
//$objWriter = new PHPExcel_Writer_Excel2007($objPHPExcel);
//$objWriter->save("_files/excel/" . $id . "_report_" . date("dmY") . ".xlsx");
$objWriter = new PHPExcel_Writer_Excel2007($objPHPExcel);
ob_end_clean();
$objWriter->save('php://output');
?>