<span style="text-align: right; float: right;">Anleitung:<b> Seite 1 von
		2</b>
</span>
<br />
<p>Es folgt nun ein dritter (und letzter) Experimentteil. Dieser besteht ebenfalls aus
	36 Runden, in denen Sie Investitionsentscheidungen fällen müssen. Auch
	in diesem Teil erhalten Sie je Runde 0.40 Euro, das Risikoprofil der
	riskanten Anlageform bleibt unverändert.</p>
<div id="back" class="button" style="float: left; display: none;"
	onmouseover="mouseover_back()" onmouseout="mouseout_back()">Zurück</div>
<div id="forward" class="button" onmouseover="mouseover_forward()"
	onmouseout="mouseout_forward()">Weiter</div>

<script>
$('#forward').click(function() {
	window.location = "<?php echo $this->url(array("controller" => "mlaexperiment2", "action" => "part2introduction")) ?>"
  });

function mouseover_forward() { document.getElementById("forward").style.backgroundColor='#ababab'; }
function mouseout_forward() { document.getElementById("forward").style.backgroundColor='#ffffff'; } 
</script>
