<h1>Experiment zu Investitionsentscheidungen</h1>
<? if($this->lastround) : ?>
<div class="alert alert-info">
<button type="button" class="close" data-dismiss="alert">×</button>
Deine Rendite vom letzten Investitionsentscheid war <?= $this->lastround->yield ?> CHF, du hast also <?= $this->lastround->yield + $this->lastround->money ?> CHF erzielt.
</div>
<? endif; ?>

<h3>Investitionsbetrag</h3>
<p>
	Es steht Ihnen folgender Betrag zur Verfügung:
	<?php echo $this->money ?>
	CHF
</p>

<div class="row">
	<div class="span6">
		<div id="formdiv" style="height: 270px;">
			<h3>Einsatz</h3>
			<?php echo $this->form ?>
		</div>
	</div>

	<div class="span6">
		<h3>Risikoprofil der riskanten Anlage</h3>
		<p>
			<img src="/images/riskprofile_250_small.png" />
		</p>
	</div>
</div>

<div class="clearboth"></div>

<script>
document.getElementById('Weiter').style.display = 'none';
$('.ui-slider-handle').hide();
</script>

<script>
function runden(x) {
	  var k = (Math.round(x * 100) / 100).toString();
	  k += (k.indexOf('.') == -1)? '.00' : '00';
	  return k.substring(0, k.indexOf('.') + 3);
	}

function setSliderAmount() {
	var values = {};
	$.each($('#mlaexperiment').serializeArray(), function(i, field) {
	    values[field.name] = field.value;
	});

	$('.ui-slider-handle').show();
	document.getElementById('Weiter').style.display = '';
	document.getElementById('investment').value = values["amount"];
	$("#investment-slider").slider("values", 0, values["amount"]);
}

document.getElementById('amount').focus();

</script>
