<h1>Investmentspiel</h1>
<p>[ENDTEXT]</p>

<div id="forward" class="button" onmouseover="mouseover_forward()"
	onmouseout="mouseout_forward()">Weiter</div>

<script>
$('#forward').click(function() {
		window.location = "<?php echo $this->url(array("controller" => "investmentgameassets", "action" => "leave")) ?>";
 });

function mouseover_forward() { document.getElementById("forward").style.backgroundColor='#ababab'; }
function mouseout_forward() { document.getElementById("forward").style.backgroundColor='#ffffff'; } 
</script>
