<script>

function runden(x) {
	  var k = (Math.round(x * 100) / 100).toString();
	  k += (k.indexOf('.') == -1)? '.00' : '00';
	  return k.substring(0, k.indexOf('.') + 3);
	}

function buy_a() {
	var asset_a_value = document.forms['investmentgameassets'].elements['asset_a_value'].value;
	var asset_a_count = document.forms['investmentgameassets'].elements['asset_a_count'].value;
	if(newmoney - asset_a_value >= 0) {
		document.forms['investmentgameassets'].elements['asset_a_count'].value++;
		newmoney -= parseFloat(asset_a_value);

		document.getElementById('newmoney').innerHTML = runden(parseFloat(newmoney)) + " Euro";
	}
}

function buy_b() {
	var asset_b_value = document.forms['investmentgameassets'].elements['asset_b_value'].value;
	var asset_b_count = document.forms['investmentgameassets'].elements['asset_b_count'].value;
	if(newmoney - asset_b_value >= 0) {
		document.forms['investmentgameassets'].elements['asset_b_count'].value++;
		newmoney -= parseFloat(asset_b_value);

		document.getElementById('newmoney').innerHTML = runden(parseFloat(newmoney)) + " Euro";
	}
}

function sell_a() {
	var asset_a_value = document.forms['investmentgameassets'].elements['asset_a_value'].value;
	var asset_a_count = document.forms['investmentgameassets'].elements['asset_a_count'].value;
	if(asset_a_count >= 0) {
		document.forms['investmentgameassets'].elements['asset_a_count'].value--;
		newmoney += parseFloat(asset_a_value);

		document.getElementById('newmoney').innerHTML = runden(parseFloat(newmoney)) + " Euro";
	}
}

function sell_b() {
	var asset_b_value = document.forms['investmentgameassets'].elements['asset_b_value'].value;
	var asset_b_count = document.forms['investmentgameassets'].elements['asset_b_count'].value;
	if(asset_b_count >= 0) {
		document.forms['investmentgameassets'].elements['asset_b_count'].value--;
		newmoney += parseFloat(asset_b_value);

		document.getElementById('newmoney').innerHTML = runden(parseFloat(newmoney)) + " Euro";
	}
}

</script>

<h1>
	Investmentspiel - Runde
	<?php echo $this->round+1?>
</h1>
<!-- Aktuelles Vermögen in Runde 0 -->
<?php if ($this->round == 0) : ?>
<p>
	Ihr aktuelles Vermögen beträgt <span
		style="font-size: 1.5em; font-weight: bold;"><?php echo $this->startingmoney ?>.00
		Euro</span>.
	<script>
var money = <?php echo $this->startingmoney ?>;
var newmoney = parseFloat(money);
</script>
</p>
<?php else : ?>
<p>
	Ihr aktuelles Vermögen beträgt <span
		style="font-size: 1.5em; font-weight: bold;"><?php echo $this->lastround->money ?>
		Euro</span>.
</p>
<script>
var money = "<?php echo $this->lastround->money ?>";
var newmoney = parseFloat(money);
</script>
<?php endif; ?>
<!-- Ende vom Aktuellen Vermögen -->

<p>
	Ihr Vermögen nach dem Handeln beträgt: <span id="newmoney"
		style="font-size: 1.5em; font-weight: bold;"><script>document.write(runden(newmoney))</script>
		Euro</span>
</p>
<br />
<?php echo $this->form ?>

