<h1>Index</h1>
<p>Welcome.</p>


<!--  
<h1>Iron Trader</h1>
<p>
Liebe Teilnehmerin, lieber Teilnehmer,<br /><br />

herzlich willkommen!
</p>
<p>
Im folgenden Investment-Spiel erhalten Sie <b>200 Euro</b>, die Sie in
mehreren Runden investieren können. Je nach Investmenterfolg können
aus den 200 Euro mehr oder weniger werden. <b>Jeder 10. Teilnehmer</b> (zufällig
ausgelost) wird genau der Betrag in echtem Geld ausgezahlt, den sie am
Ende des Spiels erzielt haben!
</p>
<p>
Bevor Sie mit dem Investment-Spiel beginnen, bitten wir Sie, ein paar
begleitende Fragen zu Ihrem Trading-Verhalten zu beantworten (ca. <b>10
Minuten</b>). Das folgende, eigentliche Investment-Spiel dauert ebenfalls
nicht länger als <b>10 Minuten</b>.
</p>
<p>
Wir möchten betonen, dass Ihre gesamten Antworten absolut <b>anonym</b> und
nur zu wissenschaftlichen Zwecken ausgewertet werden und keinesfalls
an Dritte weitergegeben werden. Für die Gewinner des Spiels greifen
wir auf die hinterlegten E-Mail-Adressen zurück, aber auch diese
Antworten werden nur anonym analysiert! Ihre Antworten haben keinen
Einfluss auf die Auslosung! Für unsere Auswertung ist es sehr wichtig,
dass Sie ehrlich und gemäß Ihren wahren Präferenzen antworten.<br /><br />

Viel Spaß und Erfolg!
</p>

<div id="forward" class="button" style="float: left" onmouseover="mouseover_forward()" onmouseout="mouseout_forward()">Weiter</div>

<script>
$('#forward').click(function() {
		window.location = "/index.php/questionnaire";
 });

function mouseover_forward() { document.getElementById("forward").style.backgroundColor='#ababab'; }
function mouseout_forward() { document.getElementById("forward").style.backgroundColor='#ffffff'; } 
</script>
-->
