<h1>Questionnaire - Fragen verwalten</h1>
<p>
<a href="/administration/questionnaire_questions/new/"><button class="btn btn-primary">Neues Treatment</button></a>
</p>
<h3>Verfügbare Treatments</h3>
<table class="table table-striped">

	<thead>
		<tr>
			<th>ID</th>
			<th>Name</th>
			<th>Beschreibung</th>
			<th>Abgeschlossen</th>
			<th>Optionen</th>
		</tr>
	</thead>
	<tbody>
		<? foreach($this->treatments as $treatment) : ?>
		<tr <? if(!$treatment->public) : ?> style="background-color: #FFB8B8;"
<? endif; ?>>
			<td><?= $treatment->id ?></td>
			<td><a href="/administration/treatment/edit/id/<?= $treatment->id ?>"><?= $treatment->name ?></a></td>
			<td><?= $treatment->description ?></td>
			<td><?= $treatment->getUsersCompletedCount() ?></td>
			<td>
				<a href="/administration/treatment/delete/id/<?= $treatment->id ?>" 
				onClick="javascript:return confirm('Sind Sie sicher, dass sie dieses Treatment l&ouml;schen m&ouml;chten? Es gehen auch alle Resultate und Datens&auml;tze verloren!')"><button class="btn btn-danger btn-mini">L&ouml;schen</button></a>
				
				<a href="/administration/treatment/reset/id/<?= $treatment->id ?>" 
				onClick="javascript:return confirm('Sind Sie sicher, dass sie alle Resultate und Datens&auml;tze dieses Treatments l&ouml;schen wollen? Diese Entscheidung ist unwiderruflich.')"><button class="btn btn-warning btn-mini">Reset</button></a>
				
				<?php if($treatment->public) : ?>
				<a href="/administration/treatment/lock/id/<?= $treatment->id ?>" 
				onClick="javascript:return confirm('Sind Sie sicher, dass Sie dieses Treatment schliessen m&ouml;chten? Neu registrierte Teilnehmer werden diesem Treatment dann nicht mehr zugewiesen.')"><i class="icon-lock"></i></a> 
				<?php else : ?> 
				<a href="/administration/treatment/unlock/id/<?= $treatment->id ?>" 
				onClick="javascript:return confirm('Sind Sie sicher, dass Sie dieses Treatment &ouml;ffnen m&ouml;chten?')"><button class="btn btn-mini">&Ouml;ffnen</button></a> 
				<?php endif; ?>
				
				<a href="<?php echo $this->url(array("controller" => "administration_questionnaire", "action" => "result", "id" => $treatment->id, "format" => "excel")) ?>"><i class="icon-download-alt"></i></a>
			</td>
		</tr>
		<?php endforeach; ?>
	</tbody>
</table>
