<h1>Experiment zu Investitionsentscheidungen</h1>
<p>
	Der Experimentteil ist nun vorüber. In diesem Teil haben Sie ein Vermögen
	von <span
		style="text-decoration: underline; font-weight: bold; font-size: 1.3em"><?php echo number_format($this->result, 2) ?>
		Euro</span> angesammelt.
</p>

<div id="forward" class="btn btn-primary">Weiter</div>

<script>
$('#forward').click(function() {
		window.location = "<?php echo $this->url(array("controller" => "mlaexperiment2", "action" => "leave")) ?>";
 });
</script>
