<span style="text-align: right; float: right;">Anleitung:<b> Seite 1 von
		5</b>
</span>
<br />
<p>Liebe Experimentteilnehmerin, lieber Experimentteilnehmer,</p>
<p>herzlich willkommen! Vor 2 Wochen haben Sie den ersten
	Experimentteil absolviert, heute folgt der zweite Teil, der ca. 25
	Minuten dauern wird (inkl. Lesen dieser Anleitung). Bitte lesen Sie die
	Anleitung sehr sorgfältig durch, auch wenn Ihnen Teile hiervon schon
	bekannt vorkommen. Sollte es in irgendeiner Form Unklarheiten geben,
	können Sie sich jederzeit an den Experimentleiter wenden.</p>
	
<div id="forward" class="btn btn-primary" style="float: right">Weiter</div>

<script>
$('#forward').click(function() {
	window.location = "<?php echo $this->url(array("controller" => "mlaexperiment2", "action" => "part1introduction")) ?>"
  });

</script>
