<h1>Administration - Treatments</h1>
<h2>
	<a
		href="<?php echo $this->url(array("controller" => "admin_treatment", "action" => "new")) ?>">Neues
		Treatment</a>
</h2>
<h2>Verfügbare Treatments</h2>
<?php foreach($this->treatments as $treatment) : ?>
<?php if($treatment->public) : ?>
<div style="background-color: #BFFFB8">
	<?php else :?>
	<div style="background-color: #E8E8E8">
		<?php endif; ?>
		<h3>
			<?php echo $treatment->name ?>
		</h3>
		<h4>
			<span style="font-size: 12px"><?php echo $treatment->description ?><br />
				Limit: <?php echo $treatment->usercount ?> / <?php echo $treatment->userlimit?><br />
				Abgeschlossen: <?php echo $treatment->getUsersCompletedCount() ?> </span><br />
			<a
				href="<?php echo $this->url(array("controller" => "admin_treatment", "action" => "edit", "id" => $treatment->id)) ?>">
				Editieren </a> &nbsp;|&nbsp; <a
				href="<?php echo $this->url(array("controller" => "admin_treatment", "action" => "delete", "id" => $treatment->id)) ?>"
				onClick="javascript:return confirm('Sind Sie sicher, dass sie dieses Treatment löschen möchten? Es gehen auch alle Resultate und Datensätze verloren!')">
				Löschen </a> &nbsp;|&nbsp; <a
				href="<?php echo $this->url(array("controller" => "admin_treatment", "action" => "reset", "id" => $treatment->id)) ?>"
				onClick="javascript:return confirm('Sind Sie sicher, dass sie alle Resultate und Datensätze dieses Treatments löschen wollen? Diese Entscheidung ist unwiderruflich.')">
				Zurücksetzen </a> &nbsp;|&nbsp;

			<?php if($treatment->public) : ?>
			<a
				href="<?php echo $this->url(array("controller" => "admin_treatment", "action" => "lock", "id" => $treatment->id)) ?>"
				onClick="javascript:return confirm('Sind Sie sicher, dass Sie dieses Treatment schliessen möchten? Neu registrierte Teilnehmer werden diesem Treatment dann nicht mehr zugewiesen.')">
				Schliessen </a>
			<?php else : ?>
			<a
				href="<?php echo $this->url(array("controller" => "admin_treatment", "action" => "unlock", "id" => $treatment->id)) ?>"
				onClick="javascript:return confirm('Sind Sie sicher, dass Sie dieses Treatment öffnen möchten?')">
				Öffnen </a>
			<?php endif; ?>
			
			 &nbsp;|&nbsp; <a href="<?php echo $this->url(array("controller" => "admin_questionnaire", "action" => "result", "id" => $treatment->id, "format" => "excel")) ?>">
				Excel </a>

		</h4>
	</div>
	<?php endforeach; ?>