<h1>
	<?php echo $this->page->title ?>
</h1>
<p>
	<?php echo $this->page->content ?>
</p>

<div id="forward" class="button" onmouseover="mouseover_forward()"
	onmouseout="mouseout_forward()">Weiter</div>

<script>
$('#forward').click(function() {
		window.location = "<?php echo $this->url(array("controller" => "static", "action" => "next")) ?>";
 });

function mouseover_forward() { document.getElementById("forward").style.backgroundColor='#ababab'; }
function mouseout_forward() { document.getElementById("forward").style.backgroundColor='#ffffff'; } 
</script>
