<h1>Userverwaltung</h1>
<h2>Nach Treatment</h2>
<?php foreach($this->treatments as $treatment) : ?>
<h3>
	<?php echo $treatment->name ?>
</h3>
<table class="admin_usertable">
	<tr>
		<th>ID</th>
		<th>Userhash / Username</th>
		<th>E-Mail</th>
		<th>Gruppe</th>
	</tr>
	<?php foreach($treatment->findManyToManyRowset("Users", "TreatmentsHasUsers") as $user) : ?>
	<tr>
		<td><?php echo $user->id ?></td>
		<td><?php echo $user->userhash ?></td>
		<td><?php echo $user->email ?></td>
		<td><?php echo $user->grp ?></td>
	</tr>
	<?php endforeach; ?>
</table>
<?php endforeach; ?>
