<h1>Willkommen</h1>
<p>Willkommen zum Behavioral Finance Test der Universität Zürich. Um an
	Studien teilzunehmen, müssen Sie sich einmalig registrieren (völlig
	unverbindlich und kostenlos!). Die Registration dauert nur ein paar
	Sekunden. Nach der Registrierung ist ein Login möglich.</p>
<p>Die Testdauer beträgt nur ca. 10 Minuten.</p>
<p>
	<b>Wichtig</b>: Ihre gesamten Daten werden ausschliesslich für
	wissenschaftliche Zwecke verwendet und keinesfalls an Dritte
	weitergegeben. Eine Auswertung erfolgt in anonymisierter Form, nur die
	Gewinner werden per E-Mail benachrichtigt. Maximal einmal erhalten Sie
	eine E-Mail-Einladung für einen weiteren Test.
</p>
<br />
<div class="wrapper">
	<div class="left_5050">
		<h1>Schritt 1: Registrieren</h1>
		<p>Für eine Registrierung ist muss eine gültige E-Mail Adresse
			angegeben werden, weitere Daten sind nicht erforderlich. Sie erhalten
			dann eine E-Mail mit dem Password für Ihren Login.</p>
		<?php echo $this->registration ?>
	</div>


	<div class="right_5050">
		<h1>Schritt 2: Teilnahme</h1>
		<?php echo $this->login ?>
	</div>
</div>

<div class="clearboth"></div>
