<h1>Experiment zu Investitionsentscheidungen</h1>
<p>
	Sie haben insgesamt einen Betrag von <span
		style="text-decoration: underline; font-weight: bold; font-size: 1.3em"><?php echo number_format($this->result, 2) ?>
		Euro</span> erzielt. Der erste Teil des Experimentes ist nun vorüber.
	Bitte denken Sie an Ihren zweiten Termin für dieses Experiment! Dann
	erhalten Sie dann auch Ihre Bezahlung.
</p>
<p>Sie können nun den Raum verlassen, bitte tun Sie das leise und stören Sie dabei nicht andere Experimentteilnehmer! Vielen Dank für Ihre bisherige Teilnahme!</p>

<div id="forward" class="button" onmouseover="mouseover_forward()"
	onmouseout="mouseout_forward()">Weiter</div>

<script>
$('#forward').click(function() {
		window.location = "<?php echo $this->url(array("controller" => "mlaexperiment", "action" => "leave")) ?>";
 });

function mouseover_forward() { document.getElementById("forward").style.backgroundColor='#ababab'; }
function mouseout_forward() { document.getElementById("forward").style.backgroundColor='#ffffff'; } 
</script>
