<span style="text-align: right; float: right;">Anleitung:<b> Seite 1 von
		5</b>
</span>
<br />
<p>Liebe Experimentteilnehmerin, lieber Experimentteilnehmer,</p>
<p>vielen Dank, dass Sie sich Zeit genommen haben, an diesem Experiment
	teilzunehmen. Das Experiment besteht aus zwei Teilen, die zu
	unterschiedlichen Terminen durchgeführt werden. Heute absolvieren Sie
	den ersten Teil, der zweite Teil folgt an dem von ihnen gewählten
	Datum. Ihren genauen Termin haben Sie bei der Anmeldung ausgewählt.</p>

<p>Der heutige Teil wird ca. 15 Minuten dauern (inkl. Lesen dieser
	Anleitung). Bitte lesen Sie die Anleitung sehr sorgfältig durch. Sollte
	es in irgendeiner Form Unklarheiten geben, können Sie sich jederzeit an
	eine Aufsichtsperson wenden.</p>
	
<div id="back" class="btn btn-primary" style="float: left; display: none;">Zurück</div>
<div id="forward" class="btn btn-primary">Weiter</div>

<script>
$('#forward').click(function() {
	window.location = "<?php echo $this->url(array("controller" => "mlaexperiment", "action" => "introduction1")) ?>"
  });
</script>
