<span style="text-align: right; float: right;">Anleitung:<b> Seite 5 von
		5</b>
</span>
<br />
<p>Die tatsächlichen Ergebnisse der riskanten Anlageform werden im
	Experiment zufällig und individuell für Sie durch den Computer unter
	Berücksichtigung der angegebenen Wahrscheinlichkeiten bestimmt. Wir
	möchten betonen, dass es hierbei keinerlei Manipulationen gibt. Sie
	können sich darauf verlassen, dass die Ergebnisse Ihrer Investitionen
	gemäss den vorgegebenen Wahrscheinlichkeiten ausgespielt werden. Die
	Ausspielungen der verschiedenen Runden sind dabei voneinander
	unabhängig, d. h. Ergebnisse früherer Runden haben keinen Einfluss auf
	die Ergebnis-Wahrscheinlichkeiten in späteren Runden.</p>
<p>Um Ihnen einen Anreiz zu geben, über Ihre Entscheidungen sorgfältig
	nachzudenken, werden wir ein Drittel der Experimentteilnehmer zufällig
	auswählen und in Euro bezahlen. Ihre Bezahlung hängt sowohl von
	Ihren Entscheidungen als auch von der zufälligen Entwicklung der
	riskanten Anlageform ab, so wie oben beschrieben. Falls Sie zur
	Auszahlung ausgelost werden, wird genau ein Experimentteil zufällig
	bestimmt, das kann der Teil heute sein, ihre Auszahlung kann aber auch
	durch den zweiten Teil dieses Experiments in zwei Wochen bestimmt
	werden. Von diesem zufällig ausgewählten Teil sind alle 36 Runden
	relevant, denn es wird Ihnen genau der Betrag in Euro ausgezahlt,
	den Sie in diesem Teil insgesamt erzielt haben.</p>
<p>Unabhängig von dieser variablen Entlohnung erhält jeder Teilnehmer
	eine fixe Entlohnung in Hähe von 5 Euro. Die Bezahlung erfolgt
	direkt am Ende des zweiten Experimentteils, also ca. in zwei Wochen.</p>
<p>Wenn Sie keine Fragen haben, klicken Sie auf "Weiter", um mit dem
	Experiment zu beginnen.</p>


<div id="forward" class="btn btn-primary" style="float: right">Weiter</div>
<div id="back" class="btn btn-primary">Zurück</div>

<script>
$('#forward').click(function() {
	window.location = "<?php echo $this->url(array("controller" => "mlaexperiment", "action" => "round")) ?>"
  });

$('#back').click(function() {
	window.location = "<?php echo $this->url(array("controller" => "mlaexperiment", "action" => "introduction3")) ?>"
  });

</script>
