<h1>Ini-Konfiguration</h1>
<h2>Allgemein</h2>
<table class="admin_ini">
	<tr>
		<td class="firstcolumn">Modus:</td>
		<td><?php if ($this->config->ibftool->labormodus) :?>Labor<?php else : ?>Web<?php endif; ?>
		</td>
	
	
	<tr>
		<td class="firstcolumn">Seitentitel:</td>
		<td><?php echo $this->config->ibftool->title ?></td>
	</tr>
</table>
<h2>Datenbank</h2>
<table class="admin_ini">
	<tr>
		<td class="firstcolumn">Name:</td>
		<td><?php echo $this->config->database->params->dbname ?></td>
	
	
	<tr>
		<td class="firstcolumn">Host:</td>
		<td><?php echo $this->config->database->params->host ?></td>
	
	
	<tr>
		<td class="firstcolumn">Tabellenprefix:</td>
		<td><?php echo $this->config->db->table_prefix ?></td>
	</tr>
</table>
