<dt id="<?php echo $this->element->getId() ?>-element">
	<label class="<?php echo $this->element->getAttrib("class"); ?>"
		for="<?php echo $this->element->getId(); ?>"><?php echo $this->element->getLabel(); ?>
	</label>
</dt>
<dd>
	<?php foreach($this->element->getMultioptions()as $key => $value) : ?>
	<label for="<?php echo $this->element->getId(); ?>-<?php echo $key ?>">
		<input type="radio" name="<?php echo $this->element->getId() ?>"
		value="<?php echo $key ?>"><span style="padding-left: 10px"><?php echo $value ?>
	</span>
	</label> <br />
	<?php endforeach; ?>
</dd>

