<h1>Investmentspiel</h1>
<p>Vielen Dank, dass
Sie am Experiment teilgenommen haben. Bitte klicken Sie auf "Beenden" und warten Sie einen
Augenblick, bis alle Teilnehmer fertig sind und der Experimentleiter
sich bei Ihnen meldet.</p>

<button id="forward" class="btn btn-primary">Beenden</button>

<script>
$('#forward').click(function() {
		window.location = "<?php echo $this->url(array("controller" => "investmentgame", "action" => "leave")) ?>";
 });
</script>
