<div>
	<div id="site1">
		<span style="text-align: right; float: right;">Anleitung:<b> Seite 1
				von 1</b>
		</span>
		<h1>Investmentspiel</h1>
		<p>Anleitung folgt</p>
		<div id="back" class="button" style="float: left; display: none;"
			onmouseover="mouseover_back()" onmouseout="mouseout_back()">Zurück</div>
		<div id="forward" class="button" onmouseover="mouseover_forward()"
			onmouseout="mouseout_forward()">Weiter</div>

		<script>
$('#forward').click(function() {
	window.location = "<?php echo $this->url(array("controller" => "mlaexperiment", "action" => "round")) ?>"
  });

function mouseover_forward() { document.getElementById("forward").style.backgroundColor='#ababab'; }
function mouseout_forward() { document.getElementById("forward").style.backgroundColor='#ffffff'; } 
</script>