<span style="text-align: right; float: right;">Anleitung:<b> Seite 1 von 1</b> </span>
<h1>Investmentspiel</h1>

<p>Anleitung folgt</p>

<div id="back" class="btn btn-primary"
	style="float: left; display: none;">Zurück</div>
<div id="forward" class="btn btn-primary">Weiter</div>

<script>
$('#forward').click(function() {
	window.location = "<?php echo $this->url(array("controller" => "investmentgame", "action" => "round")) ?>"
  });
</script>
