<h1>Investmentspiel - Runde <?php echo $this->round+1?></h1>
<div class="row">
	<div class="span6">
		<h2>Einsatz</h2>
		<p>
			In der Runde
			<?php echo $this->round+1?>
			folgenden Betrag zur Verfügung:
			<?php echo $this->money ?>
			<?php echo $this->form ?>
		</p>

	</div>

	<div class="span6">
		<h2>Risikoprofil des Investments</h2>
		<p></p>
	</div>
</div>

<script>
function runden(x) {
	  var k = (Math.round(x * 100) / 100).toString();
	  k += (k.indexOf('.') == -1)? '.00' : '00';
	  return k.substring(0, k.indexOf('.') + 3);
	}

function setSliderAmount() {
	var values = {};
	$.each($('#mlaexperiment').serializeArray(), function(i, field) {
	    values[field.name] = field.value;
	});

	$('.ui-slider-handle').show();
	document.getElementById('Weiter').style.display = '';
	document.getElementById('investment').value = values["amount"];
	$("#investment-slider").slider("values", 0, values["amount"]);
}

document.getElementById('amount').focus();

</script>
