<h1>
	Investmentspiel - Runde
	<?php echo $this->round+1?>
</h1>
<div class="wrapper">
	<div class="left_5050">
		<h1>Einsatz</h1>
		<p>
			In der Runde
			<?php echo $this->round+1?>
			folgenden Betrag zur Verfügung:
			<?php echo $this->money ?>
			<?php echo $this->form ?>
		</p>

		<script>
$(document).ready(function() {
	$( "#mla-slider" ).slider({ disabled: true });
	$('.ui-slider-handle').hide();
  });
</script>

		<span class='mla-slider-null'>0</span><span class='mla-slider-hundred'>100</span>
		<div id="mla-slider"></div>
	</div>



	<div class="right_5050">
		<h1>Risikoprofil des Investments</h1>
		<p></p>
	</div>
</div>

<div class="clearboth"></div>

<script>
document.getElementById('Weiter').style.display = 'none';
$('.ui-slider-handle').hide();
</script>

<script>
function runden(x) {
	  var k = (Math.round(x * 100) / 100).toString();
	  k += (k.indexOf('.') == -1)? '.00' : '00';
	  return k.substring(0, k.indexOf('.') + 3);
	}

function getformcontent() {
	var values = {};
	$.each($('#mlaexperiment').serializeArray(), function(i, field) {
	    values[field.name] = field.value;
	});
	
	$('.ui-slider-handle').show();
	document.getElementById('Weiter').style.display = '';
	$("#mla-slider").slider("value", values["amount"]);


}

</script>
