<div class="span12" style="text-align: right">
	<ul class="nav nav-pills">
		<?php if (Zend_Auth::getInstance()->hasIdentity()) : ?>
		<?php if (Zend_Auth::getInstance()->getIdentity()->role == "admin") : ?>
		<li><a href="/treatment/">Treatments</a></li>
		<li class="dropdown"><a href="#" class="dropdown-toggle"
			data-toggle="dropdown">Administration<b class="caret"></b>
		</a>
			<ul class="dropdown-menu">
				<li><a href="/administration/treatment/">Treatments</a></li>
				<li><a href="/administration/config/">Konfiguration</a></li>
				<li><a href="/administration/_mlaexperiment2/result/">MLA Auswertung</a>
				</li>
			</ul>
		</li>
		<?php endif; ?>
		<? endif; ?>
		<?php if (!Zend_Auth::getInstance()->hasIdentity()) : ?>
		<li><a href="/login/">Startseite</a>
		</li>
		<?php endif; ?>
		<?php if (Zend_Auth::getInstance()->hasIdentity()) : ?>
		<li><a href="/login/logout/">Logout</a> <?php endif; ?>
	
	</ul>
</div>
<? $this->inlineScript()->appendScript("$('.dropdown-toggle').dropdown()") ?>
